const CATEGORIES = {

  // ── PROFISSÕES (46 pares) ──────────────────────────────
  "Profissões": [
    { word: "Médico",              similar: "Enfermeiro" },
    { word: "Policial",            similar: "Agente Federal" },
    { word: "Cozinheiro",          similar: "Padeiro" },
    { word: "Músico",              similar: "DJ" },
    { word: "Professor",           similar: "Tutor" },
    { word: "Dentista",            similar: "Ortodontista" },
    { word: "Advogado",            similar: "Juiz" },
    { word: "Garçom",              similar: "Bartender" },
    { word: "Piloto",              similar: "Copiloto" },
    { word: "Astronauta",          similar: "Cosmonauta" },
    { word: "Bombeiro",            similar: "Salva-Vidas" },
    { word: "Espião",              similar: "Detetive" },
    { word: "Fotógrafo",           similar: "Cinegrafista" },
    { word: "Arquiteto",           similar: "Engenheiro" },
    { word: "Veterinário",         similar: "Biólogo" },
    { word: "Jornalista",          similar: "Repórter" },
    { word: "Ator",                similar: "Apresentador" },
    { word: "Cientista",           similar: "Pesquisador" },
    { word: "Mecânico",            similar: "Montador" },
    { word: "Psicólogo",           similar: "Psiquiatra" },
    { word: "Taxista",             similar: "Motorista de Ônibus" },
    { word: "Cantor",              similar: "Rapper" },
    { word: "Chef",                similar: "Confeiteiro" },
    { word: "Programador",         similar: "Designer" },
    { word: "Fazendeiro",          similar: "Agricultor" },
    { word: "Mergulhador",         similar: "Alpinista" },
    { word: "Cirurgião",           similar: "Anestesista" },
    { word: "Filósofo",            similar: "Escritor" },
    { word: "Maquiador",           similar: "Cabeleireiro" },
    { word: "Astrônomo",           similar: "Físico" },
    { word: "Encanador",           similar: "Eletricista" },
    { word: "Carpinteiro",         similar: "Marceneiro" },
    { word: "Porteiro",            similar: "Recepcionista" },
    { word: "Carteiro",            similar: "Entregador" },
    { word: "Pedreiro",            similar: "Pintor de Obras" },
    { word: "Lixeiro",             similar: "Gari" },
    { word: "Dançarino",           similar: "Coreógrafo" },
    { word: "Aeromoça",            similar: "Comissário de Bordo" },
    { word: "Jardineiro",          similar: "Paisagista" },
    { word: "Marinheiro",          similar: "Navegador" },
    { word: "Nutricionista",       similar: "Dietista" },
    { word: "Fisioterapeuta",      similar: "Quiropraxista" },
    { word: "Sommelier",           similar: "Barista" },
    { word: "Economista",          similar: "Contador" },
    { word: "Diretor de Cinema",   similar: "Produtor" },
    { word: "Tradutor",            similar: "Intérprete" },
  ],

  // ── LUGARES (42 pares) ────────────────────────────────
  "Lugares": [
    { word: "Praia",               similar: "Piscina" },
    { word: "Escola",              similar: "Universidade" },
    { word: "Hospital",            similar: "Clínica" },
    { word: "Banco",               similar: "Caixa Eletrônico" },
    { word: "Hotel",               similar: "Pousada" },
    { word: "Supermercado",        similar: "Feira" },
    { word: "Farmácia",            similar: "Drogaria" },
    { word: "Restaurante",         similar: "Lanchonete" },
    { word: "Museu",               similar: "Galeria de Arte" },
    { word: "Parque",              similar: "Jardim Botânico" },
    { word: "Igreja",              similar: "Templo" },
    { word: "Castelo",             similar: "Mansão" },
    { word: "Fazenda",             similar: "Sítio" },
    { word: "Biblioteca",          similar: "Livraria" },
    { word: "Zoológico",           similar: "Aquário" },
    { word: "Circo",               similar: "Parque de Diversões" },
    { word: "Academia",            similar: "Estúdio de Yoga" },
    { word: "Aeroporto",           similar: "Porto" },
    { word: "Delegacia",           similar: "Presídio" },
    { word: "Shopping",            similar: "Mercado" },
    { word: "Estádio",             similar: "Ginásio" },
    { word: "Laboratório",         similar: "Fábrica" },
    { word: "Quartel",             similar: "Base Militar" },
    { word: "Spa",                 similar: "Salão de Beleza" },
    { word: "Teatro",              similar: "Ópera" },
    { word: "Cemitério",           similar: "Cripta" },
    { word: "Cassino",             similar: "Boate" },
    { word: "Usina",               similar: "Refinaria" },
    { word: "Bunker",              similar: "Abrigo" },
    { word: "Ilha",                similar: "Península" },
    { word: "Praça",               similar: "Boulevard" },
    { word: "Planetário",          similar: "Observatório" },
    { word: "Cartório",            similar: "Prefeitura" },
    { word: "Posto de Saúde",      similar: "UPA" },
    { word: "Tribunal",            similar: "Fórum" },
    { word: "Pântano",             similar: "Mangue" },
    { word: "Caverna",             similar: "Gruta" },
    { word: "Floresta",            similar: "Reserva Natural" },
    { word: "Favela",              similar: "Comunidade" },
    { word: "Cais",                similar: "Píer" },
    { word: "Parque Aquático",     similar: "Clube" },
    { word: "Mercado Municipal",   similar: "Camelódromo" },
  ],

  // ── TRANSPORTES (25 pares — veículos de verdade) ──────
  "Transportes": [
    { word: "Avião",               similar: "Helicóptero" },
    { word: "Trem",                similar: "Metrô" },
    { word: "Ônibus",              similar: "Van" },
    { word: "Submarino",           similar: "Navio" },
    { word: "Moto",                similar: "Bicicleta" },
    { word: "Táxi",                similar: "Uber" },
    { word: "Foguete",             similar: "Ônibus Espacial" },
    { word: "Canoa",               similar: "Bote" },
    { word: "Balão",               similar: "Dirigível" },
    { word: "Trator",              similar: "Caminhão" },
    { word: "Lancha",              similar: "Veleiro" },
    { word: "Patinete",            similar: "Skate" },
    { word: "Teleférico",          similar: "Bondinho" },
    { word: "Carruagem",           similar: "Charrete" },
    { word: "Trem-Bala",           similar: "Monorail" },
    { word: "Hidroavião",          similar: "Planador" },
    { word: "Ambulância",          similar: "Viatura" },
    { word: "Carro de Corrida",    similar: "Fórmula 1" },
    { word: "Snowmobile",          similar: "Quad" },
    { word: "Hovercraft",          similar: "Jet Ski" },
    { word: "Bonde",               similar: "VLT" },
    { word: "Navio de Cruzeiro",   similar: "Ferry Boat" },
    { word: "Monomotor",           similar: "Ultraleve" },
    { word: "Triciclo",            similar: "Monociclo" },
    { word: "Carro de Bombeiro",   similar: "Caminhão-Pipa" },
  ],

  // ── FANTASIA & AVENTURA (28 pares) ───────────────────
  "Fantasia & Aventura": [
    { word: "Vampiro",             similar: "Zumbi" },
    { word: "Pirata",              similar: "Corsário" },
    { word: "Robô",                similar: "Androide" },
    { word: "Ninja",               similar: "Samurai" },
    { word: "Mago",                similar: "Bruxo" },
    { word: "Dragão",              similar: "Dinossauro" },
    { word: "Sereia",              similar: "Fada" },
    { word: "Guerreiro",           similar: "Cavaleiro" },
    { word: "Alien",               similar: "Extraterrestre" },
    { word: "Lobisomem",           similar: "Homem-Urso" },
    { word: "Fantasma",            similar: "Espírito" },
    { word: "Elfo",                similar: "Anão" },
    { word: "Demônio",             similar: "Diabo" },
    { word: "Super-Herói",         similar: "Vigilante" },
    { word: "Caçador",             similar: "Mercenário" },
    { word: "Oráculo",             similar: "Profeta" },
    { word: "Golem",               similar: "Titã" },
    { word: "Fênix",               similar: "Grifo" },
    { word: "Necromante",          similar: "Xamã" },
    { word: "Paladino",            similar: "Templário" },
    { word: "Ciborgue",            similar: "Mutante" },
    { word: "Feiticeiro",          similar: "Alquimista" },
    { word: "Kraken",              similar: "Leviatã" },
    { word: "Goblin",              similar: "Troll" },
    { word: "Centauro",            similar: "Minotauro" },
    { word: "Valquíria",           similar: "Anjo Guerreiro" },
    { word: "Arcanista",           similar: "Druida" },
    { word: "Portal Mágico",       similar: "Rift Dimensional" },
  ],

  // ── ESPORTES & LAZER (33 pares) ──────────────────────
  "Esportes & Lazer": [
    { word: "Futebol",             similar: "Vôlei" },
    { word: "Cinema",              similar: "Drive-in" },
    { word: "Natação",             similar: "Mergulho" },
    { word: "Tênis",               similar: "Badminton" },
    { word: "Boxe",                similar: "Karatê" },
    { word: "Skate",               similar: "Patins" },
    { word: "Basquete",            similar: "Handebol" },
    { word: "Surf",                similar: "Wakeboard" },
    { word: "Corrida",             similar: "Ciclismo" },
    { word: "Escalada",            similar: "Rapel" },
    { word: "Golfe",               similar: "Polo" },
    { word: "Xadrez",              similar: "Damas" },
    { word: "Camping",             similar: "Trilha" },
    { word: "Boliche",             similar: "Sinuca" },
    { word: "Judô",                similar: "Luta Livre" },
    { word: "Ginástica",           similar: "Acrobacia" },
    { word: "Tiro ao Alvo",        similar: "Arco e Flecha" },
    { word: "Pesca",               similar: "Caça" },
    { word: "Paintball",           similar: "Airsoft" },
    { word: "Patinação",           similar: "Esqui" },
    { word: "Rugby",               similar: "Futebol Americano" },
    { word: "Yoga",                similar: "Pilates" },
    { word: "Halterofilismo",      similar: "Crossfit" },
    { word: "Instagram",           similar: "TikTok" },
    { word: "YouTube",             similar: "Twitch" },
    { word: "Netflix",             similar: "HBO Max" },
    { word: "WhatsApp",            similar: "Telegram" },
    { word: "Podcast",             similar: "Audiobook" },
    { word: "Atletismo",           similar: "Decatlo" },
    { word: "Dança",               similar: "Ballet" },
    { word: "Cosplay",             similar: "LARP" },
    { word: "Videogame",           similar: "Jogo de Tabuleiro" },
    { word: "Esgrima",             similar: "Taekwondo" },
  ],

  // ── COMIDA & BEBIDA (30 pares) ────────────────────────
  "Comida & Bebida": [
    { word: "Pizza",               similar: "Lasanha" },
    { word: "Hambúrguer",          similar: "Hot-dog" },
    { word: "Sorvete",             similar: "Frozen Yogurt" },
    { word: "Café",                similar: "Chá" },
    { word: "Sushi",               similar: "Temaki" },
    { word: "Churrasco",           similar: "Espeto" },
    { word: "Brigadeiro",          similar: "Trufa" },
    { word: "Cerveja",             similar: "Chopp" },
    { word: "Tapioca",             similar: "Crepe" },
    { word: "Bolo",                similar: "Torta" },
    { word: "Açaí",                similar: "Smoothie" },
    { word: "Macarrão",            similar: "Risoto" },
    { word: "Sanduíche",           similar: "Wrap" },
    { word: "Salada",              similar: "Sopa" },
    { word: "Vinho",               similar: "Espumante" },
    { word: "Chocolate",           similar: "Caramelo" },
    { word: "Pipoca",              similar: "Batatinha" },
    { word: "Pudim",               similar: "Mousse" },
    { word: "Frango",              similar: "Peru" },
    { word: "Strogonoff",          similar: "Estufado" },
    { word: "Paçoca",              similar: "Amendoim" },
    { word: "Queijo",              similar: "Requeijão" },
    { word: "Iogurte",             similar: "Coalhada" },
    { word: "Whisky",              similar: "Rum" },
    { word: "Coxinha",             similar: "Pastel" },
    { word: "Feijoada",            similar: "Picadinho" },
    { word: "Tacos",               similar: "Burrito" },
    { word: "Ramen",               similar: "Pho" },
    { word: "Milkshake",           similar: "Vitamina" },
    { word: "Caldo de Cana",       similar: "Suco de Laranja" },
  ],

  // ── ANIMAIS & NATUREZA (35 pares) ────────────────────
  "Animais & Natureza": [
    { word: "Cachorro",            similar: "Lobo" },
    { word: "Floresta",            similar: "Mata" },
    { word: "Leão",                similar: "Tigre" },
    { word: "Golfinho",            similar: "Baleia" },
    { word: "Cobra",               similar: "Píton" },
    { word: "Borboleta",           similar: "Mariposa" },
    { word: "Vulcão",              similar: "Montanha" },
    { word: "Deserto",             similar: "Estepe" },
    { word: "Tubarão",             similar: "Orca" },
    { word: "Águia",               similar: "Falcão" },
    { word: "Rinoceronte",         similar: "Hipopótamo" },
    { word: "Cavalo",              similar: "Zebra" },
    { word: "Pinguim",             similar: "Foca" },
    { word: "Polvo",               similar: "Lula" },
    { word: "Jacaré",              similar: "Crocodilo" },
    { word: "Urso",                similar: "Gorila" },
    { word: "Rio",                 similar: "Lago" },
    { word: "Geleira",             similar: "Iceberg" },
    { word: "Tornado",             similar: "Furacão" },
    { word: "Corvo",               similar: "Coruja" },
    { word: "Aranha",              similar: "Escorpião" },
    { word: "Camelo",              similar: "Lhama" },
    { word: "Coral",               similar: "Alga" },
    { word: "Fogo",                similar: "Lava" },
    { word: "Flamingo",            similar: "Garça" },
    { word: "Tucano",              similar: "Papagaio" },
    { word: "Abelha",              similar: "Vespa" },
    { word: "Formiga",             similar: "Cupim" },
    { word: "Camaleão",            similar: "Lagarto" },
    { word: "Axolote",             similar: "Salamandra" },
    { word: "Ornitorrinco",        similar: "Castor" },
    { word: "Canguru",             similar: "Koala" },
    { word: "Beija-Flor",          similar: "Colibrí" },
    { word: "Savana",              similar: "Cerrado" },
    { word: "Recife de Coral",     similar: "Atol" },
  ],

  // ── OBJETOS (48 pares: clássicos + tech + veículos-objeto) ──
  "Objetos": [
    // Clássicos
    { word: "Espelho",             similar: "Vitrine" },
    { word: "Geladeira",           similar: "Freezer" },
    { word: "Sofá",                similar: "Poltrona" },
    { word: "Livro",               similar: "Revista" },
    { word: "Telefone",            similar: "Rádio" },
    { word: "Lâmpada",             similar: "Lanterna" },
    { word: "Mochila",             similar: "Maleta" },
    { word: "Óculos",              similar: "Lupa" },
    { word: "Guarda-chuva",        similar: "Capa de Chuva" },
    { word: "Relógio",             similar: "Cronômetro" },
    { word: "Chave",               similar: "Cadeado" },
    { word: "Câmera",              similar: "Binóculo" },
    { word: "Tesoura",             similar: "Faca" },
    { word: "Martelo",             similar: "Chave de Fenda" },
    { word: "Violão",              similar: "Guitarra" },
    { word: "Vela",                similar: "Tocha" },
    { word: "Cofre",               similar: "Arquivo" },
    { word: "Mapa",                similar: "Bússola" },
    { word: "Escada",              similar: "Rampa" },
    { word: "Barril",              similar: "Balde" },
    { word: "Microscópio",         similar: "Telescópio" },
    { word: "Armadilha",           similar: "Arapuca" },
    { word: "Capacete",            similar: "Elmo" },
    { word: "Ancinho",             similar: "Pá" },
    { word: "Sino",                similar: "Apito" },
    { word: "Espada",              similar: "Lança" },
    { word: "Escudo",              similar: "Armadura" },
    // Tecnologia incorporada
    { word: "Celular",             similar: "Smartphone" },
    { word: "Notebook",            similar: "Computador" },
    { word: "Tablet",              similar: "iPad" },
    { word: "Televisão",           similar: "Monitor" },
    { word: "Fone de Ouvido",      similar: "Caixa de Som" },
    { word: "Smartwatch",          similar: "Relógio Digital" },
    { word: "Impressora",          similar: "Scanner" },
    { word: "Roteador",            similar: "Modem" },
    { word: "Pendrive",            similar: "HD Externo" },
    { word: "Projetor",            similar: "Tela de Projeção" },
    { word: "Carregador",          similar: "Power Bank" },
    { word: "Teclado",             similar: "Mouse" },
    { word: "Microfone",           similar: "Amplificador" },
    { word: "Drone",               similar: "Aeromodelo" },
    // Veículos-objeto (kart, carros especiais, máquinas)
    { word: "Kart",                similar: "Quadriciclo" },
    { word: "Limusine",            similar: "Sedan" },
    { word: "Fusca",               similar: "Jipe" },
    { word: "Empilhadeira",        similar: "Guincho" },
    { word: "Motorhome",           similar: "Trailer" },
    { word: "Retroescavadeira",    similar: "Escavadeira" },
    { word: "Betoneira",           similar: "Misturador Industrial" },
    { word: "Bicicleta Ergométrica", similar: "Esteira" },
  ],
};

// "Tudo" combina todas as categorias
CATEGORIES["Tudo"] = Object.values(CATEGORIES).flat();

const CATEGORY_LIST = [
  "Tudo",
  "Profissões",
  "Lugares",
  "Transportes",
  "Fantasia & Aventura",
  "Esportes & Lazer",
  "Comida & Bebida",
  "Animais & Natureza",
  "Objetos",
];

const CATEGORY_ICONS = {
  "Tudo":                "🌍",
  "Profissões":          "💼",
  "Lugares":             "🏢",
  "Transportes":         "🚗",
  "Fantasia & Aventura": "🧙",
  "Esportes & Lazer":    "⚽",
  "Comida & Bebida":     "🍕",
  "Animais & Natureza":  "🐾",
  "Objetos":             "🪄",
};
