const CATEGORIES = {
  "Profissões": [
    { word: "Médico",           similar: "Enfermeiro" },
    { word: "Policial",         similar: "Segurança" },
    { word: "Cozinheiro",       similar: "Padeiro" },
    { word: "Músico",           similar: "DJ" },
    { word: "Professor",        similar: "Tutor" },
    { word: "Dentista",         similar: "Ortodontista" },
    { word: "Advogado",         similar: "Juiz" },
    { word: "Garçom",           similar: "Bartender" },
    { word: "Piloto",           similar: "Copiloto" },
    { word: "Astronauta",       similar: "Cosmonauta" },
    { word: "Bombeiro",         similar: "Salva-Vidas" },
    { word: "Espião",           similar: "Detetive" },
    { word: "Fotógrafo",        similar: "Cinegrafista" },
    { word: "Arquiteto",        similar: "Engenheiro" },
    { word: "Veterinário",      similar: "Biólogo" },
    { word: "Jornalista",       similar: "Repórter" },
    { word: "Ator",             similar: "Apresentador" },
    { word: "Cientista",        similar: "Pesquisador" },
    { word: "Mecânico",         similar: "Eletricista" },
    { word: "Psicólogo",        similar: "Psiquiatra" },
    { word: "Taxista",          similar: "Motorista de Ônibus" },
    { word: "Cantor",           similar: "Rapper" },
    { word: "Chef",             similar: "Confeiteiro" },
    { word: "Programador",      similar: "Designer" },
    { word: "Fazendeiro",       similar: "Pescador" },
    { word: "Mergulhador",      similar: "Alpinista" },
    { word: "Cirurgião",        similar: "Anestesista" },
    { word: "Filósofo",         similar: "Escritor" },
    { word: "Maquiador",        similar: "Cabeleireiro" },
    { word: "Astronomo",        similar: "Físico" },
    { word: "Encanador",        similar: "Eletricista" },
    { word: "Carpinteiro",      similar: "Marceneiro" },
    { word: "Porteiro",         similar: "Recepcionista" },
    { word: "Carteiro",         similar: "Entregador" },
    { word: "Pedreiro",         similar: "Pintor de Obras" },
    { word: "Lixeiro",          similar: "Gari" },
    { word: "Dançarino",        similar: "Coreógrafo" },
    { word: "Aeromoça",         similar: "Comissário de Bordo" },
    { word: "Jardineiro",       similar: "Paisagista" },
    { word: "Marinheiro",       similar: "Pescador" },
  ],

  "Lugares": [
    { word: "Praia",            similar: "Piscina" },
    { word: "Escola",           similar: "Universidade" },
    { word: "Hospital",         similar: "Clínica" },
    { word: "Banco",            similar: "Caixa Eletrônico" },
    { word: "Hotel",            similar: "Pousada" },
    { word: "Supermercado",     similar: "Feira" },
    { word: "Farmácia",         similar: "Drogaria" },
    { word: "Restaurante",      similar: "Lanchonete" },
    { word: "Museu",            similar: "Galeria de Arte" },
    { word: "Parque",           similar: "Jardim Botânico" },
    { word: "Igreja",           similar: "Templo" },
    { word: "Castelo",          similar: "Mansão" },
    { word: "Fazenda",          similar: "Sítio" },
    { word: "Biblioteca",       similar: "Livraria" },
    { word: "Zoológico",        similar: "Aquário" },
    { word: "Circo",            similar: "Parque de Diversões" },
    { word: "Academia",         similar: "Estúdio de Yoga" },
    { word: "Aeroporto",        similar: "Rodoviária" },
    { word: "Delegacia",        similar: "Presídio" },
    { word: "Shopping",         similar: "Mercado" },
    { word: "Estádio",          similar: "Ginásio" },
    { word: "Laboratório",      similar: "Fábrica" },
    { word: "Quartel",          similar: "Base Militar" },
    { word: "Spa",              similar: "Salão de Beleza" },
    { word: "Teatro",           similar: "Ópera" },
    { word: "Cemitério",        similar: "Cripta" },
    { word: "Cassino",          similar: "Boate" },
    { word: "Usina",            similar: "Refinaria" },
    { word: "Bunker",           similar: "Abrigo" },
    { word: "Ilha",             similar: "Península" },
    { word: "Praça",            similar: "Boulevard" },
    { word: "Planetário",       similar: "Observatório" },
    { word: "Cartório",         similar: "Prefeitura" },
    { word: "Posto de Saúde",   similar: "UPA" },
    { word: "Tribunal",         similar: "Fórum" },
    { word: "Estação de Trem",  similar: "Rodoviária" },
    { word: "Aquário",          similar: "Jardim Botânico" },
    { word: "Quartel",          similar: "Base Militar" },
    { word: "Cânion",           similar: "Vale" },
    { word: "Pântano",          similar: "Mangue" },
  ],

  "Transportes": [
    { word: "Avião",            similar: "Helicóptero" },
    { word: "Trem",             similar: "Metrô" },
    { word: "Ônibus",           similar: "Van" },
    { word: "Submarino",        similar: "Navio" },
    { word: "Moto",             similar: "Bicicleta" },
    { word: "Táxi",             similar: "Uber" },
    { word: "Foguete",          similar: "Ônibus Espacial" },
    { word: "Canoa",            similar: "Bote" },
    { word: "Balão",            similar: "Dirigível" },
    { word: "Trator",           similar: "Caminhão" },
    { word: "Lancha",           similar: "Veleiro" },
    { word: "Patinete",         similar: "Skate" },
    { word: "Teleférico",       similar: "Bondinho" },
    { word: "Carruagem",        similar: "Charrete" },
    { word: "Trem-Bala",        similar: "Monorail" },
    { word: "Hidroavião",       similar: "Planador" },
    { word: "Ambulância",       similar: "Viatura" },
    { word: "Carro de Corrida", similar: "Kart" },
    { word: "Snowmobile",       similar: "Quad" },
    { word: "Hovercraft",       similar: "Jet Ski" },
    { word: "Bonde",            similar: "Monotrilho" },
    { word: "Kart",             similar: "Quadriciclo" },
    { word: "Limusine",         similar: "Sedan" },
    { word: "Empilhadeira",     similar: "Guincho" },
    { word: "Motorhome",        similar: "Trailer" },
    { word: "Retroescavadeira", similar: "Trator" },
    { word: "Betoneira",        similar: "Caminhão de Obras" },
    { word: "Fusca",            similar: "Jipe" },
  ],

  "Fantasia & Aventura": [
    { word: "Vampiro",          similar: "Zumbi" },
    { word: "Pirata",           similar: "Corsário" },
    { word: "Robô",             similar: "Androide" },
    { word: "Ninja",            similar: "Samurai" },
    { word: "Mago",             similar: "Bruxo" },
    { word: "Dragão",           similar: "Dinossauro" },
    { word: "Sereia",           similar: "Fada" },
    { word: "Guerreiro",        similar: "Cavaleiro" },
    { word: "Alien",            similar: "Extraterrestre" },
    { word: "Lobisomem",        similar: "Homem-Urso" },
    { word: "Fantasma",         similar: "Espírito" },
    { word: "Elfo",             similar: "Anão" },
    { word: "Demônio",          similar: "Diabo" },
    { word: "Super-Herói",      similar: "Vigilante" },
    { word: "Caçador",          similar: "Mercenário" },
    { word: "Oráculo",          similar: "Profeta" },
    { word: "Golem",            similar: "Titã" },
    { word: "Fênix",            similar: "Grifo" },
    { word: "Necromante",       similar: "Xamã" },
    { word: "Paladino",         similar: "Templário" },
  ],

  "Esportes & Lazer": [
    { word: "Futebol",          similar: "Vôlei" },
    { word: "Cinema",           similar: "Streaming" },
    { word: "Natação",          similar: "Mergulho" },
    { word: "Tênis",            similar: "Badminton" },
    { word: "Boxe",             similar: "Karatê" },
    { word: "Skate",            similar: "Patins" },
    { word: "Videogame",        similar: "Jogo de Tabuleiro" },
    { word: "Basquete",         similar: "Handebol" },
    { word: "Surf",             similar: "Wakeboard" },
    { word: "Corrida",          similar: "Ciclismo" },
    { word: "Escalada",         similar: "Rapel" },
    { word: "Golfe",            similar: "Polo" },
    { word: "Xadrez",           similar: "Damas" },
    { word: "Camping",          similar: "Trilha" },
    { word: "Boliche",          similar: "Sinuca" },
    { word: "Judô",             similar: "Luta Livre" },
    { word: "Ginástica",        similar: "Acrobacia" },
    { word: "Tiro ao Alvo",     similar: "Arco e Flecha" },
    { word: "Pesca",            similar: "Caça" },
    { word: "Paintball",        similar: "Airsoft" },
    { word: "Patinação",        similar: "Esqui" },
  ],

  "Comida & Bebida": [
    { word: "Pizza",            similar: "Lasanha" },
    { word: "Hambúrguer",       similar: "Hot-dog" },
    { word: "Sorvete",          similar: "Frozen Yogurt" },
    { word: "Café",             similar: "Chá" },
    { word: "Sushi",            similar: "Temaki" },
    { word: "Churrasco",        similar: "Espeto" },
    { word: "Brigadeiro",       similar: "Trufa" },
    { word: "Cerveja",          similar: "Chopp" },
    { word: "Tapioca",          similar: "Crepe" },
    { word: "Bolo",             similar: "Torta" },
    { word: "Açaí",             similar: "Smoothie" },
    { word: "Macarrão",         similar: "Risoto" },
    { word: "Sanduíche",        similar: "Wrap" },
    { word: "Salada",           similar: "Sopa" },
    { word: "Vinho",            similar: "Espumante" },
    { word: "Chocolate",        similar: "Caramelo" },
    { word: "Pipoca",           similar: "Batatinha" },
    { word: "Pudim",            similar: "Mousse" },
    { word: "Frango",           similar: "Peru" },
    { word: "Strogonoff",       similar: "Estufado" },
    { word: "Paçoca",           similar: "Amendoim" },
    { word: "Queijo",           similar: "Requeijão" },
    { word: "Iogurte",          similar: "Coalhada" },
    { word: "Whisky",           similar: "Rum" },
  ],

  "Animais & Natureza": [
    { word: "Cachorro",         similar: "Lobo" },
    { word: "Floresta",         similar: "Mata" },
    { word: "Leão",             similar: "Tigre" },
    { word: "Golfinho",         similar: "Baleia" },
    { word: "Cobra",            similar: "Lagarto" },
    { word: "Borboleta",        similar: "Mariposa" },
    { word: "Vulcão",           similar: "Montanha" },
    { word: "Deserto",          similar: "Savana" },
    { word: "Tubarão",          similar: "Orca" },
    { word: "Águia",            similar: "Falcão" },
    { word: "Rinoceronte",      similar: "Hipopótamo" },
    { word: "Cavalo",           similar: "Zebra" },
    { word: "Pinguim",          similar: "Foca" },
    { word: "Polvo",            similar: "Lula" },
    { word: "Jacaré",           similar: "Crocodilo" },
    { word: "Urso",             similar: "Gorila" },
    { word: "Rio",              similar: "Lago" },
    { word: "Geleira",          similar: "Iceberg" },
    { word: "Tornado",          similar: "Furacão" },
    { word: "Corvo",            similar: "Coruja" },
    { word: "Aranha",           similar: "Escorpião" },
    { word: "Camelo",           similar: "Lhama" },
    { word: "Coral",            similar: "Alga" },
    { word: "Fogo",             similar: "Lava" },
    { word: "Flamingo",         similar: "Garça" },
    { word: "Tucano",           similar: "Papagaio" },
    { word: "Abelha",           similar: "Vespa" },
    { word: "Formiga",          similar: "Cupim" },
    { word: "Camaleão",         similar: "Lagarto" },
    { word: "Axolote",          similar: "Salamandra" },
    { word: "Ornitorrinco",     similar: "Castor" },
    { word: "Recife de Coral",  similar: "Fundo do Mar" },
    { word: "Savana",           similar: "Cerrado" },
    { word: "Cânion",           similar: "Desfiladeiro" },
  ],

  "Tecnologia": [
    { word: "Celular",               similar: "Smartphone" },
    { word: "Notebook",              similar: "Computador" },
    { word: "Tablet",                similar: "iPad" },
    { word: "Televisão",             similar: "Monitor" },
    { word: "Videogame",             similar: "Console" },
    { word: "Fone de Ouvido",        similar: "Caixa de Som" },
    { word: "Drone",                 similar: "Helicóptero" },
    { word: "Smartwatch",            similar: "Relógio Digital" },
    { word: "Impressora",            similar: "Scanner" },
    { word: "Roteador",              similar: "Modem" },
    { word: "Instagram",             similar: "TikTok" },
    { word: "WhatsApp",              similar: "Telegram" },
    { word: "Inteligência Artificial", similar: "Robô" },
    { word: "Realidade Virtual",     similar: "Realidade Aumentada" },
    { word: "Criptomoeda",           similar: "NFT" },
    { word: "Pendrive",              similar: "HD Externo" },
    { word: "Microfone",             similar: "Câmera" },
    { word: "Projetor",              similar: "Tela de Projeção" },
    { word: "Carregador",            similar: "Power Bank" },
    { word: "Teclado",               similar: "Mouse" },
  ],

  "Objetos": [
    { word: "Espelho",          similar: "Vitrine" },
    { word: "Geladeira",        similar: "Freezer" },
    { word: "Sofá",             similar: "Poltrona" },
    { word: "Livro",            similar: "Revista" },
    { word: "Telefone",         similar: "Rádio" },
    { word: "Lâmpada",          similar: "Lanterna" },
    { word: "Mochila",          similar: "Maleta" },
    { word: "Óculos",           similar: "Lupa" },
    { word: "Guarda-chuva",     similar: "Capa de Chuva" },
    { word: "Relógio",          similar: "Cronômetro" },
    { word: "Chave",            similar: "Cadeado" },
    { word: "Câmera",           similar: "Binóculo" },
    { word: "Tesoura",          similar: "Faca" },
    { word: "Martelo",          similar: "Chave de Fenda" },
    { word: "Violão",           similar: "Guitarra" },
    { word: "Televisão",        similar: "Monitor" },
    { word: "Vela",             similar: "Tocha" },
    { word: "Cofre",            similar: "Arquivo" },
    { word: "Mapa",             similar: "Bússola" },
    { word: "Escada",           similar: "Rampa" },
    { word: "Barril",           similar: "Balde" },
    { word: "Teclado",          similar: "Controle" },
    { word: "Microscópio",      similar: "Telescópio" },
    { word: "Armadilha",        similar: "Arapuca" },
    { word: "Capacete",         similar: "Elmo" },
    { word: "Ancinho",          similar: "Pá" },
    { word: "Bússola",          similar: "GPS" },
    { word: "Sino",             similar: "Apito" },
    { word: "Espada",           similar: "Lança" },
    { word: "Escudo",           similar: "Armadura" },
  ],
};

// "Tudo" combina todas as categorias
CATEGORIES["Tudo"] = Object.values(CATEGORIES).flat();

const CATEGORY_LIST = [
  "Tudo",
  "Profissões",
  "Lugares",
  "Transportes",
  "Fantasia & Aventura",
  "Esportes & Lazer",
  "Comida & Bebida",
  "Animais & Natureza",
  "Objetos",
  "Tecnologia",
];

const CATEGORY_ICONS = {
  "Tudo":                "🌍",
  "Profissões":          "💼",
  "Lugares":             "🏢",
  "Transportes":         "🚗",
  "Fantasia & Aventura": "🧙",
  "Esportes & Lazer":    "⚽",
  "Comida & Bebida":     "🍕",
  "Animais & Natureza":  "🐾",
  "Objetos":             "🪄",
  "Tecnologia":          "💻",
};
